
Running CU for variant 0...
  Running k=1, iteration 1/1...
Traceback (most recent call last):
  File "scripts/capture_time_memory_real_graphs.py", line 130, in <module>
    run_experiments(args.algorithm, args.iterations, args.output_dir)
  File "scripts/capture_time_memory_real_graphs.py", line 71, in run_experiments
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gtime'
